name = "MTR:Massive Building"
author = "X341"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17cd0683a9c91f0ee4fe0a7afb3ab5da91316dd5677913e8a6d1e58d1892ceb8"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
