name = "MTR:Massive Building"
author = "X341"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf97aeec0dffd71fa0c2b85ec7df8200ec89bf2d0e4afa04a62eaf203b7cc6c4"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
